name: denki
description: calc of electricity
version: 0.0.2
homepage: https://github.com/nishizumi-lab/libs/tree/master/flutter/01_package/calc_wareki
repository: https://github.com/nishizumi-lab/libs/tree/master/flutter/01_package/calc_wareki


environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
