name: stat
description: Calculate statistical values for list- sum, max, min, mean, median, standard deviation, and standard error.
version: 0.0.7
homepage: https://github.com/tanaka0079/dart/stat
environment:
  sdk: '>=2.0.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

#dev_dependencies:
#  test: ^1.5.1