name: electric
description: electric package
version: 0.0.6
homepage: https://github.com/nishizumi-lab/libs/tree/master/flutter/01_package/electric
repository: https://github.com/nishizumi-lab/libs/tree/master/flutter/01_package/electric

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
