name: array_util
description: array utils for flutter
version: 0.0.1
homepage: https://github.com/nishizumi-lab/libs/tree/master/flutter/01_package/array_util
repository: https://github.com/nishizumi-lab/libs/tree/master/flutter/01_package/array_util

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

